#! /bin/bash

# The first argument is the build type desired.
# Debug or Release.
BUILD_TYPE=$1

# Debug is the default built type
if [ ! $BUILD_TYPE ]; then
    BUILD_TYPE="Debug"
fi

# Directory names
CMAKE_DIR="gen"
BIN_DIR="bin"
CONTENT_DIR="content"

# Executable name
EXECUTABLE="Whisperer"

# If this is a release build, nuke everything first
if [ "$BUILD_TYPE" == "Release" ]; then
    rm -r $CMAKE_DIR
    rm -r $BIN_DIR
fi

# Create directories for CMake files and binaries
# if they don't already exist.
if [ ! -d $CMAKE_DIR ]; then
    # Files generated by cmake
    mkdir $CMAKE_DIR
fi

if [ ! -d $BIN_DIR ]; then
    # Game binaries
    mkdir $BIN_DIR
fi

# Generate the build system with CMake using
# the desired build configuration
cd $CMAKE_DIR
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

# Build the game
make

# Move the executable into the binary directory
mv $EXECUTABLE ../$BIN_DIR
# Copy the game assets into the binary directory
# if they aren't already there
cd ..
cp -ru $CONTENT_DIR $BIN_DIR

# If this is a release build, make a zip file
if [ "$BUILD_TYPE" == "Release" ]; then
    mv $BIN_DIR $EXECUTABLE
    zip -r ${EXECUTABLE}.zip $EXECUTABLE
    mv $EXECUTABLE $BIN_DIR

    # Move the zip file to the bin directory
    mv ${EXECUTABLE}.zip $BIN_DIR
fi
